### ISSUE TITLE
There is already a collection named "cronHistory" error

### ISSUE THREAD

**Issue by kolyasya** [quavedev/meteor-packages#1]
Hey, I replaced the package with

`meteor remove littledata:synced-cron && meteor add quave:synced-cron`

And now I get such error:

<img width="967" alt="image" src="https://github.com/quavedev/meteor-packages/assets/3371143/78d898e7-edc5-47f8-9584-30016272fcf1">

I tried to drop the collection, but after restart I still get the same result.

Rolling back to `littledata:synced-cron` fixes the issue.

Also I tried to disable all the custom SyncedCron code I have (`SyncedCron.config`, `SyncedCron.start` and etc.)
It didn't help.

I'm testing it with Meteor 2.x. Is that an issue?

**Comment by filipenevola** [comment]
@joaovictornsv I think you got a similar error, right?

And yes, it could be related with Meteor 2.

I'll take a look in the next 2 weeks.

**Comment by joaovictornsv** [comment]
> @joaovictornsv I think you got a similar error, right?
> 
> And yes, it could be related with Meteor 2.
> 
> I'll take a look in the next 2 weeks.

Yes, I got a similar error.

In my case, I changed the collection name to be able to work with `quave:synced-cron`.

**Comment by filipenevola** [comment]
> In my case, I needed to changed the collection name to be able to work with `quave:synced-cron`.

That shouldn't be necessary, I'll check soon.

**Comment by filipenevola** [comment]
@kolyasya I'm not getting this error.

There was a version where MongoDB threw a different user error, but that's fixed in our current versions.

Are you running an older MongoDB version?

Please reopen the issue if you're still experiencing this problem.

BTW, we just released a new version with new features. Check them out here: https://github.com/quavedev/meteor-packages/blob/main/synced-cron/CHANGELOG.md#209-2024-10-07
